In [ ]:
! pip install numpy  ### ye global eneviornment mai install hui hai(C Drive ke andr)

In [1]:
print("hello")

hello


In [2]:
import numpy as np
np.__version__

'2.4.6'



### What is NumPy?

NumPy is a powerful Python library used for:

Numerical calculations
Working with arrays
Mathematical operations
Scientific computing
Data analysis

NumPy ka full form hai:

Numerical Python



# NumPy Summary Table

| Topic | Description | Example |
|---|---|---|
| NumPy | Numerical Python library | `import numpy as np` |
| Array | Stores multiple values | `np.array([1,2,3])` |
| 1D Array | Single dimensional array | `[1 2 3]` |
| 2D Array | Rows and columns | `[[1,2],[3,4]]` |
| ndarray | Main NumPy object | `type(arr)` |
| ndim | Checks dimensions | `arr.ndim` |
| shape | Returns rows & columns | `arr.shape` |
| size | Total elements count | `arr.size` |
| dtype | Data type of array | `arr.dtype` |
| zeros() | Creates zero array | `np.zeros((2,2))` |
| ones() | Creates ones array | `np.ones((2,2))` |
| arange() | Creates range array | `np.arange(1,10)` |
| linspace() | Equal spaced values | `np.linspace(1,10,5)` |
| reshape() | Changes array shape | `arr.reshape(2,3)` |
| Indexing | Access single element | `arr[0]` |
| Slicing | Access multiple elements | `arr[1:4]` |
| Addition | Adds arrays | `a+b` |
| Subtraction | Subtract arrays | `a-b` |
| Multiplication | Multiply arrays | `a*b` |
| Division | Divide arrays | `a/b` |
| sum() | Finds total sum | `np.sum(arr)` |
| max() | Finds maximum value | `np.max(arr)` |
| min() | Finds minimum value | `np.min(arr)` |
| mean() | Finds average | `np.mean(arr)` |
| Advantages | Fast & memory efficient | Used in Data Science |
| Applications | ML, AI, Statistics | Data Analysis |



In [3]:
lst=(list(range(1,20))) ### list hetogenous hoti hai aur array homo aur array jyada fasster hot hai list se

In [4]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [5]:
type(lst)

list

In [6]:
arr=np.array(lst)

In [7]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [8]:
lst=[1,2,3,4,5]
arr=np.array(lst)

In [9]:
type(arr)

numpy.ndarray

In [16]:
from numpy import *
arr=array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr=np.array([range(1,20)])

In [12]:
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19]])

In [18]:

arr = np.arange(1,21)
type(arr)

numpy.ndarray

In [19]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [21]:
arr=np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
arr=np.ones(12)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [27]:
arr=np.zeros((5,10))  ###rows=5 and col=10
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
print(arr.ndim)

2


In [33]:

arr=np.linspace(1,10,5)
print(arr)
print(type(arr))

[ 1.    3.25  5.5   7.75 10.  ]
<class 'numpy.ndarray'>


In [38]:
import numpy as np
arr= np.arange(0,30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [39]:
arr=arr.reshape(10,3)

In [42]:
arr=arr.reshape(6,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [44]:
arr=np.random.randint(1,5,10) ###1=starting point  ###5=ending point ###10- random generated point frequency
arr

array([2, 1, 1, 4, 3, 2, 4, 3, 4, 3], dtype=int32)

In [45]:
np.random.randint(1,5,(5,6))

array([[4, 4, 2, 3, 3, 3],
       [1, 4, 4, 4, 3, 3],
       [4, 1, 3, 2, 4, 3],
       [1, 4, 1, 4, 1, 4],
       [1, 2, 3, 3, 3, 1]], dtype=int32)

In [46]:
arr=np.random.random(10)

In [47]:
arr

array([0.31022329, 0.42384525, 0.69042599, 0.90199949, 0.07206283,
       0.72221816, 0.55209735, 0.88313018, 0.59685641, 0.72463742])

In [49]:
arr=np.random.random((10,3))
arr

array([[0.44687206, 0.56959213, 0.12518938],
       [0.58756707, 0.70706889, 0.4620701 ],
       [0.29200678, 0.05722779, 0.82241975],
       [0.81041961, 0.15847011, 0.25288633],
       [0.63899789, 0.47727481, 0.52231247],
       [0.40558104, 0.78918082, 0.61374327],
       [0.14247366, 0.74934634, 0.20314192],
       [0.5982876 , 0.33682486, 0.561485  ],
       [0.58967034, 0.04370166, 0.75780396],
       [0.17049709, 0.28001089, 0.71698021]])

In [51]:
arr=np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [52]:
print("shape of array:-",arr.shape)
print("size of array:-",arr.size) ##size
print("number of dim:-",arr.ndim) ###dimension
print("type of item:-",arr.dtype)

shape of array:- (12, 5)
size of array:- 60
number of dim:- 2
type of item:- int64


In [53]:
lst=[[1,2,3],[4,5,6]]
lst

[[1, 2, 3], [4, 5, 6]]

In [55]:
arr=np.array(lst) ### 2d list directly convereted to an array
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
arr=np.arange(60).reshape(15,4)

In [59]:
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]
 [48 49 50 51]
 [52 53 54 55]
 [56 57 58 59]]


In [63]:
print("the size of array is:-", arr.size)
print("te shape of array is:-", arr.shape)
print("the datatype of array is:-", arr.dtype)

the size of array is:- 60
te shape of array is:- (15, 4)
the datatype of array is:- int64


In [70]:
arr.transpose()

array([[ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56],
       [ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57],
       [ 2,  6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58],
       [ 3,  7, 11, 15, 19, 23, 27, 31, 35, 39, 43, 47, 51, 55, 59]])

In [71]:
arr.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56],
       [ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57],
       [ 2,  6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58],
       [ 3,  7, 11, 15, 19, 23, 27, 31, 35, 39, 43, 47, 51, 55, 59]])

In [ ]:
arr[0,0]  ### first 0 for row and second for col

np.int64(0)

In [73]:
arr[0][0]

np.int64(0)

In [74]:
arr[-1][-1]

np.int64(59)

In [76]:
arr[11,-1]

np.int64(47)

In [77]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59]])

In [78]:
arr[2:4]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [82]:
arr[2:4,3:]

array([[11],
       [15]])

In [85]:
arr[0:9,3:4]

array([[ 3],
       [ 7],
       [11],
       [15],
       [19],
       [23],
       [27],
       [31],
       [35]])

In [86]:
arr[-1,-1]=100

In [87]:
arr

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17,  18,  19],
       [ 20,  21,  22,  23],
       [ 24,  25,  26,  27],
       [ 28,  29,  30,  31],
       [ 32,  33,  34,  35],
       [ 36,  37,  38,  39],
       [ 40,  41,  42,  43],
       [ 44,  45,  46,  47],
       [ 48,  49,  50,  51],
       [ 52,  53,  54,  55],
       [ 56,  57,  58, 100]])

In [88]:
print("shape of array:-",arr.shape)
print("size of array:-",arr.size) ##size
print("number of dim:-",arr.ndim) ###dimension
print("type of item:-",arr.dtype)


shape of array:- (15, 4)
size of array:- 60
number of dim:- 2
type of item:- int64


In [20]:
### 3D array
import numpy as np     #### each table=5  no. of rows in it=15 and col=3
arr=np.arange(225).reshape(5,15,3)

In [3]:
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [7]:
arr[0][0][0]

np.int64(0)

In [8]:
arr[-1]

array([[180, 181, 182],
       [183, 184, 185],
       [186, 187, 188],
       [189, 190, 191],
       [192, 193, 194],
       [195, 196, 197],
       [198, 199, 200],
       [201, 202, 203],
       [204, 205, 206],
       [207, 208, 209],
       [210, 211, 212],
       [213, 214, 215],
       [216, 217, 218],
       [219, 220, 221],
       [222, 223, 224]])

In [9]:
arr[-1][-1]

array([222, 223, 224])

In [10]:
arr[-1][-1][-1]

np.int64(224)

In [13]:
arr[1,0]

array([45, 46, 47])

In [14]:
arr[0:5,0]

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [18]:
arr[0:5,0,0]

array([  0,  45,  90, 135, 180])

In [19]:
arr[0:5,2:4]

array([[[  6,   7,   8],
        [  9,  10,  11]],

       [[ 51,  52,  53],
        [ 54,  55,  56]],

       [[ 96,  97,  98],
        [ 99, 100, 101]],

       [[141, 142, 143],
        [144, 145, 146]],

       [[186, 187, 188],
        [189, 190, 191]]])

In [21]:
arr[0:5,3:5]

array([[[  9,  10,  11],
        [ 12,  13,  14]],

       [[ 54,  55,  56],
        [ 57,  58,  59]],

       [[ 99, 100, 101],
        [102, 103, 104]],

       [[144, 145, 146],
        [147, 148, 149]],

       [[189, 190, 191],
        [192, 193, 194]]])

In [22]:
arr[0:5,0:15,-1]

array([[  2,   5,   8,  11,  14,  17,  20,  23,  26,  29,  32,  35,  38,
         41,  44],
       [ 47,  50,  53,  56,  59,  62,  65,  68,  71,  74,  77,  80,  83,
         86,  89],
       [ 92,  95,  98, 101, 104, 107, 110, 113, 116, 119, 122, 125, 128,
        131, 134],
       [137, 140, 143, 146, 149, 152, 155, 158, 161, 164, 167, 170, 173,
        176, 179],
       [182, 185, 188, 191, 194, 197, 200, 203, 206, 209, 212, 215, 218,
        221, 224]])

In [24]:
arr[0:5,14,-1]

array([ 44,  89, 134, 179, 224])

In [26]:
arr[0:5,-1,-1]

array([ 44,  89, 134, 179, 224])

In [28]:
print("the size of array is:-", arr.size)
print("te shape of array is:-", arr.shape)
print("the datatype of array is:-", arr.dtype)
print("the number of dim", arr.ndim)

the size of array is:- 225
te shape of array is:- (5, 15, 3)
the datatype of array is:- int64
the number of dim 3


In [33]:
arr

array([[[100,   1,   2],
        [100,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[100,  46,  47],
        [100,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[100,  91,  92],
        [100,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [34]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([7,8,9,10,11,12])

In [36]:
arr3=arr1*arr2

arr4=arr1+arr2

arr5=arr1/arr2

arr6=arr1%arr2

arr7=arr1-arr2



In [45]:
arr1=np.array([1,12,35,7,2,9])
arr2=np.array([7,8,9,10,11,12])

In [49]:
arr2=arr1.sort()
print("sorted array=",arr2)

sorted array= None


In [52]:
arr1=np.arange(225)
arr1

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [53]:
arr1.reshape(5,15,3)

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11